module.exports = {
    messageKeys: {
        code_5000: 'An error occured while authentiation.',
        code_5001: 'An error occured while creating user.',
        code_5002: 'Internal server error.',
        code_5003: 'File not uploaded. Error on creating file.',
        code_5004: 'Error in reading file.',
        code_4000: 'User already exists.',
        code_4001: 'Invalid credentials.',
        code_4002: 'Incomplete data.',
        code_4003: 'User already logged in somewhere.',
        code_4004: 'Unauthorized access.',
        code_4005: 'Invalid token.',
        code_4006: 'Token missing.',
        code_4007: 'Invalid Link.',
        code_2000: 'success',
        code_2001: 'User created successfully.',
        code_2002: 'Session created.',
        code_2003: 'Successful login.',
        code_2004: 'Mail sent successfully.',
    },
    regExp: {
        dateTime: /^\d{4}-(?:0[0-9]{1}|1[0-2]{1})-[0-9]{2}T\d{2}:\d{2}:\d{2}(\.\d{3})?Z$/,
        date: /^\d{4}-(?:0[0-9]{1}|1[0-2]{1})-[0-9]{2}$/,
        time: /^\d{2}:\d{2}:\d{2}$/,
        email: /^(?:[\w\!\#\$\%\&\'\*\+\-\/\=\?\^\`\{\|\}\~]+\.)*[\w\!\#\$\%\&\'\*\+\-\/\=\?\^\`\{\|\}\~]+@(?:(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-](?!\.)){0,61}[a-zA-Z0-9]?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9\-](?!$)){0,61}[a-zA-Z0-9]?)|(?:\[(?:(?:[01]?\d{1,2}|2[0-4]\d|25[0-5])\.){3}(?:[01]?\d{1,2}|2[0-4]\d|25[0-5])\]))$/,
        ipAddress: /^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/,
        ipv6: /^\s*((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?\s*$/,
        uri: /^[a-zA-Z][a-zA-Z0-9+-.]*:[^\s]*$/,
        hostName: /^(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])$/,

        alpha: /^[a-zA-Z]+$/,
        alphanumeric: /^[a-zA-Z0-9]+$/,
        phone: /^\+(?:[0-9] ?){6,14}[0-9]$/,
        albumPrivilege: /^[0-5]/,
        albumType: /^[0-5]/,
        businessProfileRating: /^[1-5]/,
        videoAlbumType: /^[0-2]/,
    },
    systemMessage : {
        MobileExists : "{0} already exists",
        SavesuccessMessage : "{0} added successfully",
        SaveErrorMessage : "{0} not added",
        DeletesuccessMessage : "{0} deleted successfully",
        DeleteErrorMessage : "{0} not deleted",
        UpdatesuccessMessage : "{0} updates successfully",
        UpdateErrorMessage : "{0} not updated",
        GetsuccessMessage : "{0} fetch successfully",
        GetErrorMessage : "{0} not found",
        UploadSuccessMessage : "{0} uploaded successfully",
        UploadErrorMessage : "{0} not uploaded",
        InvalidInputMessage : "Invalid input value",
        AuthenticationFailureMessage : "Authentication Failed",
        InvalidCredentialMessage : "Invalid {0} and {1}",
        TryAgainMessage : "Try Again, Something goes wrong!",
        MailsuccessMessage : "Mail sent successfully!",
        MailErrorMessage : "Mail not sent.",
        LogoutSuccessMessage : "Logout successfully",
        LogoutErrorMessage : "Error in logout",
        LoginSuccessMessage : "Login successfully",
        //LoginErrorMessage : "Error in login",
        LoginErrorMessage : "Login failed",
        ResetPasswordSuccessMessage : "Password reset successfully",
        ResetPasswordErrorMessage : "Password not reset",
        ResetOldPasswordErrorMessage : "Old Password not match",
        ResetPasswordLinkSuccessMessage : "Reset password link send successfully",
        ResetPasswordLinkErrorMessage : "Reset password link not send",
        ForgotPasswordLinkSuccessMessage : "Forgot password link send successfully",
        ForgotPasswordLinkErrorMessage : "Forgot password link not send",
        ForgotPasswordLinkAlreadySentMessage : "Forgot password link sent already, try with that",
        ForgotPasswordLinkExpireMessage : "Forgot password link expired,try another time",
        ForgotPasswordSuccessMessage : "Password change successfully",
        ForgotPasswordErrorMessage : "Password not change",
    
        //Front Message for Web, Mobile
        InvalidPlatformErrorMessage : "Login with invalid platform",
        InvalidUsernameErrorMessage : "Invalid username",
        InvalidUserIdErrorMessage : "Invalid user id",
        OTPSendSuccessMessage : "OTP sent successfully",
        OTPSendErrorMessage : "OTP not sent",
        OTPVerifySuccessMessage : "OTP verify successfully",
        OTPVerifyErrorMessage : "OTP not verified",
        SocialLoginMobileMessage : "This mobile already linked with gmail or facebook",
        SocialLoginEmailMessage : "This email already linked with gmail or facebook",
        JobRenewSuccessMessage : "Job renewed successfully",
        JobRenewErrorMessage : "Job not renewed",
        EditProfileSuccessMessage : "Profile update successfully",
        EditProfileErrorMessage : "Profile not updated",
        CredentialNotMatch : "Credential does not match",
        UpdateViewCountSuccessMessage: "Ads view updated successfully",
        UpdateViewCountErrorMessage: "Ads view not updated",
    }
};